/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package calc;

/**
 *
 * @author Shital
 */
public class Calculator extends javax.swing.JFrame {
    double firstnumber, secondnumber, ans;
    char choice;
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        setTitle("Calculator");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Division = new javax.swing.JButton();
        Minus = new javax.swing.JButton();
        Multiply = new javax.swing.JButton();
        Dot = new javax.swing.JButton();
        Plus = new javax.swing.JButton();
        Zero = new javax.swing.JButton();
        Eight = new javax.swing.JButton();
        Nine = new javax.swing.JButton();
        Cos = new javax.swing.JButton();
        Sin = new javax.swing.JButton();
        Tan = new javax.swing.JButton();
        Cosec = new javax.swing.JButton();
        Sec = new javax.swing.JButton();
        Cot = new javax.swing.JButton();
        Percentage = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Sqroot = new javax.swing.JButton();
        Pow = new javax.swing.JButton();
        Moniter = new javax.swing.JTextField();
        Seven = new javax.swing.JButton();
        Fact = new javax.swing.JButton();
        Four = new javax.swing.JButton();
        Three = new javax.swing.JButton();
        Two = new javax.swing.JButton();
        One = new javax.swing.JButton();
        Six = new javax.swing.JButton();
        Five = new javax.swing.JButton();
        Asin = new javax.swing.JButton();
        Acos = new javax.swing.JButton();
        Atan = new javax.swing.JButton();
        Log = new javax.swing.JButton();
        Exp = new javax.swing.JButton();
        Clear1 = new javax.swing.JButton();
        Result = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Division.setText("/");
        Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisionActionPerformed(evt);
            }
        });

        Minus.setText("-");
        Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusActionPerformed(evt);
            }
        });

        Multiply.setText("*");
        Multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplyActionPerformed(evt);
            }
        });

        Dot.setText(".");
        Dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DotActionPerformed(evt);
            }
        });

        Plus.setText("+");
        Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusActionPerformed(evt);
            }
        });

        Zero.setText("0");
        Zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroActionPerformed(evt);
            }
        });

        Eight.setText("8");
        Eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EightActionPerformed(evt);
            }
        });

        Nine.setText("9");
        Nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NineActionPerformed(evt);
            }
        });

        Cos.setText("Cos");
        Cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CosActionPerformed(evt);
            }
        });

        Sin.setText("Sin");
        Sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinActionPerformed(evt);
            }
        });

        Tan.setText("Tan");
        Tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanActionPerformed(evt);
            }
        });

        Cosec.setText("Cosec");
        Cosec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CosecActionPerformed(evt);
            }
        });

        Sec.setText("Sec");
        Sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecActionPerformed(evt);
            }
        });

        Cot.setText("Cot");
        Cot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CotActionPerformed(evt);
            }
        });

        Percentage.setText("%");
        Percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PercentageActionPerformed(evt);
            }
        });

        Clear.setText("D");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        Sqroot.setText("Sqroot");
        Sqroot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SqrootActionPerformed(evt);
            }
        });

        Pow.setText("Pow");
        Pow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowActionPerformed(evt);
            }
        });

        Moniter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoniterActionPerformed(evt);
            }
        });

        Seven.setText("7");
        Seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenActionPerformed(evt);
            }
        });

        Fact.setText("Fact");
        Fact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FactActionPerformed(evt);
            }
        });

        Four.setText("4");
        Four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourActionPerformed(evt);
            }
        });

        Three.setText("3");
        Three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeActionPerformed(evt);
            }
        });

        Two.setText("2");
        Two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoActionPerformed(evt);
            }
        });

        One.setText("1");
        One.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneActionPerformed(evt);
            }
        });

        Six.setText("6");
        Six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixActionPerformed(evt);
            }
        });

        Five.setText("5");
        Five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveActionPerformed(evt);
            }
        });

        Asin.setText("Sin'");
        Asin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsinActionPerformed(evt);
            }
        });

        Acos.setText("Cos'");
        Acos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcosActionPerformed(evt);
            }
        });

        Atan.setText("Tan'");
        Atan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtanActionPerformed(evt);
            }
        });

        Log.setText("Log");
        Log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogActionPerformed(evt);
            }
        });

        Exp.setText("Exp");
        Exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpActionPerformed(evt);
            }
        });

        Clear1.setBackground(new java.awt.Color(255, 51, 51));
        Clear1.setText("C");
        Clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear1ActionPerformed(evt);
            }
        });

        Result.setText("=");
        Result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultActionPerformed(evt);
            }
        });

        jButton2.setText("ln");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("+ -");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMenu2.setText("Change Mode");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Table");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Pow)
                        .addGap(8, 8, 8)
                        .addComponent(Log, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Exp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Sqroot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Fact, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Dot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Seven))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Zero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Eight))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nine, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Division, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Percentage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Cos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Sec, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Asin)
                            .addGap(14, 14, 14)
                            .addComponent(Acos)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Atan)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Tan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Cot, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Moniter, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Clear1)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(One, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Two, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(57, 57, 57))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Four)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Five)
                                    .addGap(18, 18, 18)
                                    .addComponent(Six, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(86, 86, 86)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Three, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Plus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addComponent(Sin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Cosec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(Clear1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Clear))
                    .addComponent(Moniter))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(One)
                    .addComponent(Two)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Plus)
                        .addComponent(Result)
                        .addComponent(Three)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Four)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Minus)
                                .addComponent(jButton2)
                                .addComponent(jButton3)
                                .addComponent(Six)
                                .addComponent(Five)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Seven)
                            .addComponent(Eight)
                            .addComponent(Nine)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Multiply)
                                .addComponent(Sin)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Dot)
                            .addComponent(Zero)
                            .addComponent(Division)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Percentage)
                                .addComponent(Sec)
                                .addComponent(Cos)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Asin)
                            .addComponent(Acos)
                            .addComponent(Atan)
                            .addComponent(Tan)
                            .addComponent(Cot)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Cosec)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sqroot)
                    .addComponent(Fact)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Log)
                        .addComponent(Exp)
                        .addComponent(Pow)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisionActionPerformed
        firstnumber = Double.parseDouble(Moniter.getText());
        Moniter.setText("");
        choice = '/';
    }//GEN-LAST:event_DivisionActionPerformed

    private void MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusActionPerformed
        String str=Moniter.getText();
        firstnumber = Double.parseDouble(str);
        Moniter.setText("");
        /*if(str == null){
            Moniter.setText(Minus.getText());
        }*/
        choice = '-';
    }//GEN-LAST:event_MinusActionPerformed

    private void MultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplyActionPerformed
        firstnumber = Double.parseDouble(Moniter.getText());
        Moniter.setText("");
        choice = '*';
    }//GEN-LAST:event_MultiplyActionPerformed

    private void DotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DotActionPerformed
        Moniter.setText(Moniter.getText() + Dot.getText());
    }//GEN-LAST:event_DotActionPerformed

    private void PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusActionPerformed
        
        firstnumber += Double.parseDouble(Moniter.getText());
        Moniter.setText("");
        choice = '+';
    }//GEN-LAST:event_PlusActionPerformed

    private void ZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZeroActionPerformed
        Moniter.setText(Moniter.getText() + Zero.getText());
    }//GEN-LAST:event_ZeroActionPerformed

    private void EightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EightActionPerformed
        Moniter.setText(Moniter.getText() + Eight.getText());
    }//GEN-LAST:event_EightActionPerformed

    private void NineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NineActionPerformed
        Moniter.setText(Moniter.getText() + Nine.getText());
    }//GEN-LAST:event_NineActionPerformed

    private void CosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CosActionPerformed
        firstnumber = Double.parseDouble(Moniter.getText());
        Moniter.setText("Cos " + String.valueOf(firstnumber));
        choice = 'c';

    }//GEN-LAST:event_CosActionPerformed

    private void SinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinActionPerformed
        firstnumber = Double.parseDouble(Moniter.getText());
        Moniter.setText("Sin " + String.valueOf(firstnumber));
        choice = 's';
    }//GEN-LAST:event_SinActionPerformed

    private void TanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanActionPerformed
        firstnumber = Double.parseDouble(Moniter.getText());
        Moniter.setText("Tan " + String.valueOf(firstnumber));
        choice = 't';
    }//GEN-LAST:event_TanActionPerformed

    private void CosecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CosecActionPerformed
        firstnumber = Double.parseDouble(Moniter.getText());
        Moniter.setText("Cosec " + String.valueOf(firstnumber));
        choice = 'C';
    }//GEN-LAST:event_CosecActionPerformed

    private void SecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecActionPerformed
        firstnumber = Double.parseDouble(Moniter.getText());
        Moniter.setText("Sec " + String.valueOf(firstnumber));
        choice = 'S';
    }//GEN-LAST:event_SecActionPerformed

    private void CotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CotActionPerformed
        firstnumber = Double.parseDouble(Moniter.getText());
        Moniter.setText("Cot " + String.valueOf(firstnumber));
        choice = 'T';
    }//GEN-LAST:event_CotActionPerformed

    private void PercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PercentageActionPerformed
        firstnumber = Double.parseDouble(Moniter.getText());
        Moniter.setText("");
        choice = '%';
    }//GEN-LAST:event_PercentageActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        int num;
        firstnumber = Double.parseDouble(Moniter.getText());
        secondnumber = firstnumber%10;
        secondnumber = secondnumber/10;
        firstnumber = firstnumber/10 - secondnumber;
     
        Moniter.setText(String.valueOf((int)firstnumber));
    }//GEN-LAST:event_ClearActionPerformed

    private void SqrootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SqrootActionPerformed
        firstnumber = Double.parseDouble(Moniter.getText());
        Moniter.setText("Sqrt("+String.valueOf(firstnumber)+")");
        choice = 'r';
    }//GEN-LAST:event_SqrootActionPerformed

    private void PowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowActionPerformed
        firstnumber = Double.parseDouble(Moniter.getText());
        Moniter.setText("");
        choice = 'p';
    }//GEN-LAST:event_PowActionPerformed

    private void MoniterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoniterActionPerformed

    }//GEN-LAST:event_MoniterActionPerformed

    private void SevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SevenActionPerformed
        Moniter.setText(Moniter.getText() + Seven.getText());
    }//GEN-LAST:event_SevenActionPerformed

    private void FactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FactActionPerformed
        firstnumber = Double.parseDouble(Moniter.getText());
        Moniter.setText(String.valueOf(firstnumber) + "!");
        choice = 'f';
    }//GEN-LAST:event_FactActionPerformed

    private void FourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourActionPerformed
        Moniter.setText(Moniter.getText() + Four.getText());
    }//GEN-LAST:event_FourActionPerformed

    private void ThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeActionPerformed
        Moniter.setText(Moniter.getText() + Three.getText());
    }//GEN-LAST:event_ThreeActionPerformed

    private void TwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoActionPerformed
        Moniter.setText(Moniter.getText() + Two.getText());
    }//GEN-LAST:event_TwoActionPerformed

    private void OneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneActionPerformed

        Moniter.setText(Moniter.getText() + One.getText());

    }//GEN-LAST:event_OneActionPerformed

    private void SixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixActionPerformed
        Moniter.setText(Moniter.getText() + Six.getText());
    }//GEN-LAST:event_SixActionPerformed

    private void FiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiveActionPerformed
        Moniter.setText(Moniter.getText() +Five.getText());
    }//GEN-LAST:event_FiveActionPerformed

    private void ExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpActionPerformed
       firstnumber = Double.parseDouble(Moniter.getText());
       Moniter.setText("e^("+String.valueOf(firstnumber)+")");
       choice = 'E';
    }//GEN-LAST:event_ExpActionPerformed

    private void AsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsinActionPerformed
       firstnumber = Double.parseDouble(Moniter.getText());
       Moniter.setText("Sin' (" + String.valueOf(firstnumber) + ")");
       choice = 'i';      
    }//GEN-LAST:event_AsinActionPerformed

    private void AcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcosActionPerformed
        firstnumber = Double.parseDouble(Moniter.getText());
        Moniter.setText("Cos'("+String.valueOf(firstnumber)+")");
        choice = 'o';
    }//GEN-LAST:event_AcosActionPerformed

    private void AtanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtanActionPerformed
        firstnumber = Double.parseDouble(Moniter.getText());
        Moniter.setText("Tan'("+String.valueOf(firstnumber)+")");
        choice = 'a';
    }//GEN-LAST:event_AtanActionPerformed

    private void ResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultActionPerformed
        switch(choice){
            case '+':
                secondnumber =Double.parseDouble(Moniter.getText());
                ans = firstnumber + secondnumber;
                break;
            case '-':
                secondnumber =Double.parseDouble(Moniter.getText());
                ans = firstnumber - secondnumber;
                break;
            case '*':
                secondnumber =Double.parseDouble(Moniter.getText());
                ans = firstnumber * secondnumber;
                break;
            case '/':
                secondnumber =Double.parseDouble(Moniter.getText());
                ans = firstnumber / secondnumber ;
                break;
            case '%':
                secondnumber =Double.parseDouble(Moniter.getText());
                ans = firstnumber % secondnumber;
                break;
            case 's':
                secondnumber = Math.toRadians(firstnumber);
                ans = Math.sin(secondnumber);    
                break;
            case 'c':
                secondnumber = Math.toRadians(firstnumber);
                ans = Math.cos(secondnumber);
            case 't':
                secondnumber = Math.toRadians(firstnumber);
                ans = Math.sin(secondnumber) / Math.cos(secondnumber);
                break;
            case 'C':
                secondnumber = Math.toRadians(firstnumber);
                ans = Math.sin(secondnumber) / Math.cos(secondnumber);
                break;
            case 'S':
                secondnumber = Math.toRadians(firstnumber);
                ans = 1 / Math.cos(secondnumber);
                break;
            case 'T':
                secondnumber = Math.toRadians(firstnumber);
                ans = Math.cos(secondnumber) / Math.sin(secondnumber);
                break;
            case 'r':
                ans = Math.sqrt(firstnumber);
                break;
            case 'p':
                secondnumber = Double.parseDouble(Moniter.getText());
                ans = Math.pow(firstnumber,secondnumber);
                break;
            case 'f':
                ans = 1;
                for(int i=1;i<=firstnumber;i++){
                    ans *= i;
                }
                break;
            case 'i':
                ans = Math.asin(firstnumber);
                ans = Math.toDegrees(ans);
                break;
            case 'o':
                ans = Math.acos(firstnumber);
                ans = Math.toDegrees(ans);
                break;
            case 'a':
                ans = Math.atan(firstnumber);
                ans = Math.toDegrees(ans);
                break;
            case 'L':
                ans = Math.log10(firstnumber);
                break;
            case 'E':
                ans = Math.exp(firstnumber);
                break;
            case 'n':
                ans = Math.log(firstnumber);
                break;
            default :
            //JOptionPane.showMessageDialog(null,"Unwanted Operation");
            break;
        }
        firstnumber =0;
        Moniter.setText(String.valueOf(ans));
    }//GEN-LAST:event_ResultActionPerformed

    private void Clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear1ActionPerformed
        Moniter.setText("");
    }//GEN-LAST:event_Clear1ActionPerformed

    private void LogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogActionPerformed
       firstnumber = Double.parseDouble(Moniter.getText());
       Moniter.setText("Log10("+String.valueOf(firstnumber)+")");
       choice = 'L';
    }//GEN-LAST:event_LogActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        firstnumber = Double.parseDouble(Moniter.getText());
        int i=-1;
        firstnumber *= i;
        Moniter.setText(String.valueOf(firstnumber));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        firstnumber = Double.parseDouble(Moniter.getText());
        Moniter.setText("ln(" + String.valueOf(firstnumber)+")");
        choice = 'n';
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Table frame2 = new Table();
        frame2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acos;
    private javax.swing.JButton Asin;
    private javax.swing.JButton Atan;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Clear1;
    private javax.swing.JButton Cos;
    private javax.swing.JButton Cosec;
    private javax.swing.JButton Cot;
    private javax.swing.JButton Division;
    private javax.swing.JButton Dot;
    private javax.swing.JButton Eight;
    private javax.swing.JButton Exp;
    private javax.swing.JButton Fact;
    private javax.swing.JButton Five;
    private javax.swing.JButton Four;
    private javax.swing.JButton Log;
    private javax.swing.JButton Minus;
    private javax.swing.JTextField Moniter;
    private javax.swing.JButton Multiply;
    private javax.swing.JButton Nine;
    private javax.swing.JButton One;
    private javax.swing.JButton Percentage;
    private javax.swing.JButton Plus;
    private javax.swing.JButton Pow;
    private javax.swing.JButton Result;
    private javax.swing.JButton Sec;
    private javax.swing.JButton Seven;
    private javax.swing.JButton Sin;
    private javax.swing.JButton Six;
    private javax.swing.JButton Sqroot;
    private javax.swing.JButton Tan;
    private javax.swing.JButton Three;
    private javax.swing.JButton Two;
    private javax.swing.JButton Zero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
